"""Export a knowledge graph to formats other tools understand (GraphML, Cypher, CSV)."""
from __future__ import annotations

import csv
import json
import os
import re

import networkx as nx

from knowledge_graph.visualization import build_graph_data

EXPORT_FORMATS = ("json", "csv", "graphml", "cypher")


def export_graph(triples, output_html, formats, graph_data=None):
    """Write the requested export files next to ``output_html``; returns the paths written."""
    base = os.path.splitext(output_html)[0]
    graph_data = graph_data or build_graph_data(triples)
    written = []
    for fmt in formats:
        if fmt == "json":
            path = f"{base}.json"
            with open(path, "w", encoding="utf-8") as f:
                json.dump(triples, f, indent=2, ensure_ascii=False)
        elif fmt == "csv":
            path = f"{base}.csv"
            write_csv(triples, path)
        elif fmt == "graphml":
            path = f"{base}.graphml"
            write_graphml(triples, graph_data, path)
        elif fmt == "cypher":
            path = f"{base}.cypher"
            write_cypher(triples, graph_data, path)
        else:
            raise ValueError(f"Unknown export format {fmt!r}; choose from {', '.join(EXPORT_FORMATS)}")
        written.append(path)
    return written


def parse_formats(spec):
    """Turn ``"graphml,cypher"`` into a validated list (``json`` is always written by the CLI)."""
    formats = [f.strip().lower() for f in spec.split(",") if f.strip()]
    unknown = [f for f in formats if f not in EXPORT_FORMATS]
    if unknown:
        raise ValueError(f"Unknown export format(s) {unknown}; choose from {', '.join(EXPORT_FORMATS)}")
    return formats


def write_csv(triples, path):
    fields = ["subject", "predicate", "object", "subject_type", "object_type", "inferred", "method", "via",
              "chunk", "document", "source"]
    with open(path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for t in triples:
            row = {k: t.get(k, "") for k in fields}
            row["inferred"] = "true" if t.get("inferred") else "false"
            writer.writerow(row)


def _node_attrs(graph_data):
    return {n["id"]: n for n in graph_data["nodes"]}


def _community_names(graph_data):
    return {c["id"]: c.get("name") or f"Community {c['id'] + 1}" for c in graph_data["meta"]["communities"]}


def write_graphml(triples, graph_data, path):
    """GraphML for Gephi, yEd, Cytoscape: typed nodes with community/degree, edges with provenance."""
    nodes = _node_attrs(graph_data)
    names = _community_names(graph_data)
    G = nx.MultiDiGraph()
    for node_id, n in nodes.items():
        G.add_node(node_id, label=node_id, type=n.get("type", ""), community=n["community"],
                   community_name=names.get(n["community"], ""), degree=n["degree"], color=n["color"])
    for t in triples:
        G.add_edge(t["subject"], t["object"], label=t["predicate"], predicate=t["predicate"],
                   inferred=bool(t.get("inferred", False)), method=t.get("method", "") or "",
                   via=t.get("via", "") or "", source=t.get("source", "") or "", document=t.get("document", "") or "")
    nx.write_graphml(G, path, encoding="utf-8")


_LABEL_SAFE = re.compile(r"[^A-Za-z0-9_]+")


def cypher_label(entity_type):
    return "".join(part.capitalize() for part in _LABEL_SAFE.sub(" ", entity_type or "Entity").split()) or "Entity"


def cypher_rel_type(predicate):
    rel = _LABEL_SAFE.sub("_", predicate.strip()).strip("_").upper()
    if not rel:
        rel = "RELATED_TO"
    if rel[0].isdigit():
        rel = "R_" + rel
    return rel


def _cypher_string(value):
    return json.dumps("" if value is None else str(value), ensure_ascii=False)


def write_cypher(triples, graph_data, path):
    """Idempotent Cypher (MERGE) script for Neo4j: one label per entity type, one relationship type per predicate."""
    nodes = _node_attrs(graph_data)
    names = _community_names(graph_data)
    lines = ["// Generated by ai-knowledge-graph. Run with: cypher-shell -f this_file.cypher",
             "CREATE CONSTRAINT kg_entity_name IF NOT EXISTS FOR (e:Entity) REQUIRE e.name IS UNIQUE;", ""]
    for node_id, n in nodes.items():
        label = cypher_label(n.get("type"))
        lines.append(
            f"MERGE (e:Entity {{name: {_cypher_string(node_id)}}}) "
            f"SET e:{label}, e.type = {_cypher_string(n.get('type', ''))}, e.community = {n['community']}, "
            f"e.community_name = {_cypher_string(names.get(n['community'], ''))}, e.degree = {n['degree']};"
        )
    lines.append("")
    for t in triples:
        props = {"predicate": t["predicate"], "inferred": bool(t.get("inferred", False))}
        for key in ("method", "via", "source", "document"):
            if t.get(key):
                props[key] = t[key]
        if t.get("chunk"):
            props["chunk"] = int(t["chunk"])
        prop_text = ", ".join(
            f"{k}: {json.dumps(v, ensure_ascii=False) if not isinstance(v, bool) else str(v).lower()}"
            for k, v in props.items())
        lines.append(
            f"MATCH (a:Entity {{name: {_cypher_string(t['subject'])}}}), (b:Entity {{name: {_cypher_string(t['object'])}}}) "
            f"MERGE (a)-[r:{cypher_rel_type(t['predicate'])} {{predicate: {_cypher_string(t['predicate'])}}}]->(b) "
            f"SET r += {{{prop_text}}};"
        )
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
